### ISSUE TITLE
Salvattore crashing in Safari

### ISSUE THREAD

**Issue by exaroth** [rnmp/salvattore#101]
I get an error when appending elements in Safari browser, Chrome and Firefox are working properly,

Error details:

    [Error] TypeError: 'undefined' is not an object (evaluating 'fragments[i].children.length')
	next_element_column_index (salvattore.js, line 382)
	append_to_next_fragment (salvattore.js, line 423)
	forEach
	append_elements (salvattore.js, line 422)
	appendIndexImages (scripts.js, line 114)
	... rest is Jquery crap

The data is loaded dynamically when user scrolls down the page, so this might cause the problem.

**Edit**

Managed to fix this problem by simply removing `fragments[i].children.length` from `salvattore.js` as the length was always 0 in my case anyways.

**Comment by MariusRumpf** [comment]
Since this is already in the source I assume this is fixed.
