### ISSUE TITLE
Is ie8 support still coming?

### ISSUE THREAD

**Issue by scooterlord** [rnmp/salvattore#116]
Hello, first of all thanks for the plugin, works like magic!

You mentioned on the intro site that ie8 support is supposed to come but I noticed the plugin hasn't updated for almost a year. Is ie8 support still on schedule to come??

**Comment by scooterlord** [comment]
Hello again! Any luck on this one?

**Comment by yuepywu** [comment]
Hi, is IE8 support still coming?

**Comment by MariusRumpf** [comment]
There is nobody working on it as far as I know. Support for Windows XP has been discontinued a while back, so I would not expect so.

**Comment by scooterlord** [comment]
thanks for the reply! In the meantime I dropped support for ie8 myself on my projects...
