### ISSUE TITLE
dist files (1.0.5) are not updated

### ISSUE THREAD

**Issue by akobashikawa** [rnmp/salvattore#125]
I note Salvattore available in dist (v1.0.5 https://raw.github.com/rnmp/salvattore/master/dist/salvattore.min.js and https://raw.github.com/rnmp/salvattore/master/dist/salvattore.js) has a bug in appendElements (next_element_column_index is undefined).

This bug is fixed in src (right name is nextElementColumnIndex).

I think is needed run Grunt and update dist files.

**Comment by MariusRumpf** [comment]
I just regenerated the dist files, assume it is fixed with 302f35a4eedb26056ab189edf3a74adde3aea626 otherwise open an issue again. Thanks a lot.
