### ISSUE TITLE
Bower always fetch 1.0.5 instead of 1.0.7

### ISSUE THREAD

**Issue by tentacode** [rnmp/salvattore#156]
Hello, and thanks for the lib, it suits us well !

Just an issue with bower getting an outdated version of the lib (api is not the same as in the doc, for example `append_elements` VS `appendElements`). I also have a naughty bug with append elements not working in safari and phantomjs (which should have been resolved in the most recent version).

Here is my bower.json :

```json
{
  "dependencies": {
    "salvattore": "~1.0.7"
  }
}
```

And when I look into dist/salvattore.min.js, the version is 1.0.5.

Meanwhile I installed it with `npm install rnmp/salvattore` and it was ok. Would prefer having in bower though.

**Comment by MariusRumpf** [comment]
This should be fixed with the new 1.0.8 release just made.
