### ISSUE TITLE
[object CSSImportRule] breaks script in IE9

### ISSUE THREAD

**Issue by unre4l** [rnmp/salvattore#159]
Hi, 
when an `[object CSSImportRule]` is parsed in the code below, ie9 will throw a ```not implemented``` error.

```javascript
if (rule.media && rule.cssRules && self.mediaRuleHasColumnsSelector(rule.cssRules)) {
  newMediaRules.push(rule);
}
``` 
`rule.media` attribute is causing the `not implemented` error and breaks the whole script.
A simple try catch does the job, but is not the prettiest solution.

```javascript
try{
  if (rule.media && rule.cssRules && self.mediaRuleHasColumnsSelector(rule.cssRules)) {
    newMediaRules.push(rule);
  }
}catch(e){
  console.log(e);
}
```

**Comment by MariusRumpf** [comment]
Could reproduce this using an `@import` rule in the css file with a google web font in IE9.
Could also only fix this with a try-catch block. This is cause by `rule.media`.
