### ISSUE TITLE
not displaying in microsoft edge

### ISSUE THREAD

**Issue by ray86** [rnmp/salvattore#160]
I downloaded windows 10 recently and decided to check out my site built with the salvattore plugin on the new Microsoft edge, but unfortunately I keep getting this error Unable to get property 'length' of undefined or null reference, salvattore.js (382,5). don't know what could be the problem.

**Comment by MariusRumpf** [comment]
I cannot find a problem with the reference sites I checked. In latest version line 382 of salvattore.js is a while loop which could not throw such an error. Are you using the latest version?
Can you provide us with with a link to your site, so we can check it out?

**Comment by ray86** [comment]
thanks, just got the latest version and its working perfectly now.

**Comment by MariusRumpf** [comment]
Perfect, good to hear that solved it.
