### ISSUE TITLE
Ugly holes at page bottom

### ISSUE THREAD

**Issue by droganov** [rnmp/salvattore#161]
It looks like Salvattore doesn't take cell height into account and sorts straightforward cell1 to coll1, cell2 to coll2 and again.

When cell height vary, Salvatore makes ugly holes at the bottom of the page.

4 columns example:

![image](https://cloud.githubusercontent.com/assets/1375299/9411727/5b47af1c-4830-11e5-9fe7-e76f66efcd60.png)

2 columns example:
![image](https://cloud.githubusercontent.com/assets/1375299/9411768/b0a0aff4-4830-11e5-8185-71999be99a21.png)

In both cases first column expected to be higher then the last column.

**Comment by MariusRumpf** [comment]
The plugin does only take order into account for now. A version that takes height into account is planed, see #70.
