### ISSUE TITLE
Div height 3px greater than contained image height?

### ISSUE THREAD

**Issue by j-greig** [rnmp/salvattore#42]

**Comment by bramvandenbulcke** [comment]
I have a similar problem. My images have the same dimensions but the height of the text is different. At the top row of the images, there is a difference in height of 5px between the images on the outside and the images on the inside. In the 3 column version, the difference applies to the second row. In the two column version, there is no problem. 
![salvattore-3px-difference](https://cloud.githubusercontent.com/assets/8631196/12207019/9f79d5ca-b644-11e5-9e57-afc283636c1e.png)

I tried justifying the content, so the first and the last row have no margin or padding at the outside. When I remove this, the height problem dissapears (but of course, I want the content to justify).
