### ISSUE TITLE
Add unregister_grid/unregisterGrid method

### ISSUE THREAD

**Issue by MoOx** [rnmp/salvattore#46]
I'm on a case where I can switch from grid to list & was wondering if it can be an option to unregister a grid on an element.When switching to list, I just empty this dom element & reappend all item, CSS does the rest. It's working except when I resize the window (salvattore is still trying to update the grid, that doesn't contains column anymore).
Since my dom container have some specific classes, I want to avoid to create a new element.
Is this doable easily ?

**Comment by tykko87** [comment]
Could someone please look into this? Thanks.

**Comment by MoOx** [comment]
If you want something done right, you have to do it yourself.

Anyway this project looks dead. You should do that using css column.
