### ISSUE TITLE
No change on window resize.

### ISSUE THREAD

**Issue by EvaRune** [rnmp/salvattore#54]
Hi, I'm not a javascript specialist, I'm just a designer who uses cool scripts like this one :)

My problem here is that the columns don't recalculate when media queries breakpoints are reached on window resize, I have to reload the page to see the change. I don't know what I should do.

**Comment by Dzoge** [comment]
I just noticed that reponsive grid  is not working when I open the HTML file from my local disk and I have to refresh in order to view responsive views.
But when I copy the files over to the webserver and open the same HTML file from there, it works and follows the browser window resize...

Though, no errors are logged in the console when I open it locally.

**Comment by pudgereyem** [comment]
What I found is using `::after` without using `[data-columns]`, in your css – it wont work.

So this will work:

````
@media screen and (min-width: 769px) {
  .grid[data-columns]::before {
    content: '3 .column.size-1of3';
  }
}
```

But not this:

```
@media screen and (min-width: 769px) {
  &::before {
    content: '3 .column.size-1of3';
  }
}
```

**Comment by michaeltrilford** [comment]
That's interesting @pudgereyem 

@Dzoge Yeh that is correct, you just have to remember that on the local, it only seems to work on refresh.

Every time I got to use Salvattore, I rediscover this. Mind of a sieve.

**Comment by ymdahi** [comment]
Running into this issue now - any help would be greatly appreciated: http://gcn.fcad.ryerson.ca

The data-columns attribute is not being updated on window resize. I've tried changing the css to match the example on the site, but that didn't work.

Thanks in advance for your help.

**Comment by Stolzenhain** [comment]
> What I found is […] without using `[data-columns]`, in your css – it wont work.

… confirming as well – thanks for the hint; <del>maybe this should have been noted better in the doc</del>*. You can still use `&` placeholders BTW, only also crediting the attribute like this:

```
@media screen and (min-width: 769px) {
  &[data-placeholder]:before {
    content: '3 .column.size-1of3';
  }
}
```

\* ok, I guess you could't expect more than the note already existing:

> with the [data-columns] attribute selector included, Salvattore relies on this

**Comment by michaeltrilford** [comment]
I can't remember fully, but the JS calls data-columns to generate the additional markup?

Just copy and paste that HTML structure they provide, and everything should just work.

**Comment by Stolzenhain** [comment]
Yep, I got it to work. Depending on your project your content needs to rely on additional markup though and it's nice to be able to iterate this via SASS. But everything's cool as long a s you include `data-columns`.

**Comment by aslanoglou** [comment]
i have the same problem, i did everything you say but i still have the problem
http://clientarea.spocstudio.com/@attiko_parko/elephants/asian_culture_en.html

**Comment by Stolzenhain** [comment]
@aslanoglou: I _suppose_ it's your `default.css` code in line `93`, where you define the `:before` content outside of a media query, overriding the max/min settings – as @veteze notes, this doesn't work. 

I can't change the code on your site to verify this, though.

**Comment by naeemsaleem** [comment]
Hey guys, having the same problem here, the columns are not changing unless i reload the page - I'd appreciate any insight that can be given!

[http://bowclub.co/en/shop](http://bowclub.co/en/shop)

**Comment by sujitsah** [comment]
its not working for size 1-2 when i reduce it to mobile size that is 468px
