### ISSUE TITLE
Not always when mediaquery changes, salvattore changes

### ISSUE THREAD

**Issue by oscarotero** [rnmp/salvattore#60]
Hi.
I'm using this library in a project. On reload the page works fine but on resize the window, the mediaqueries fails. I've checking the code and found this line: https://github.com/rnmp/salvattore/blob/master/src/salvattore.js#L133. On remove the "if", it works fine.
The problem is that not always when a media query changes, it match with the current state. Sometimes the media query match previously and stop to match now. You can check it here:

http://jsfiddle.net/oscarotero/L3NXK/

This is a typical mobile first layout. On resize the result window the column numbers does not change.

**Comment by vinaydasari** [comment]
My problem is, the css file with media queries  is loaded using oclazyload and is not present on the page. The function  `self.getStylesheets()`  loads the styles present on the page and reacts to media changes. How can I achieve this with lazy loaded css files?

**Comment by vinaydasari** [comment]
I was able to solve it by calling `rescanMediaQueries()` again.
