### ISSUE TITLE
Feature website

### ISSUE THREAD

**Issue by Klayemore** [rnmp/salvattore#65]
Hi, I've gone live with a new site, which is my best use of Salvattore: http://goholiday.com.au/photography

It's a good example of combining Salvattore with Lazyload and Colorbox.

Thanks for the awesome plugin.

Cheers,
Klaye

**Comment by antonsarov** [comment]
Voting to close that one as the site is no longer available

**Comment by MariusRumpf** [comment]
Same here, no longer available. Thanks for the notification.
