### ISSUE TITLE
3 .column.size-1of3 displayed before the 3 columns

### ISSUE THREAD

**Issue by emugel** [rnmp/salvattore#77]
Hi, thanks for salvattore, it's a great plugin.
However I encounter a small problem. I guess this should be fixable in a way or another.

Here's the problem:

In Firefox 28 (OSX), I got "3 .column.size-1of3" (without quotes) displayed just before my 3 columns. I also see it displayed in Chrome except in Chrome it would quickly disappear after 200ms or so.

Any workaround? 
TIA, and keep up the good work!

**Comment by mjcampagna** [comment]
You could also just set color: transparent; for the text.

**Comment by emugel** [comment]
Thanks.

**Comment by lassecph** [comment]
Could we put this in the examples/salvattore.css?
