### ISSUE TITLE
Salvattore deletes markup

### ISSUE THREAD

**Issue by wguldin** [rnmp/salvattore#86]
Hi, I'm using the recreate_columns method that was publicly exposed in a pull request to recreate the salvattore layout when I'm ajaxing between two different pages. 

This is working, but Salvattore is stripping out a container div from my markup when this method runs, and I'm not sure why.

The markup I'm expecting:

    <div class="salvattore-column-1">
        <div class="container">
            // Content Here
        </div>
    </div>

    <div class="salvattore-column-2">
        <div class="container">
            // Content Here
        </div>
    </div>

The markup I'm getting:

    <div class="salvattore-column-1">
            // Content Here, container gone
    </div>

    <div class="salvattore-column-2">
            // Content Here, container gone
    </div>

If the actual markup is important, here is the contents of one 'container' div. 'Account-content' is my container. This div gets removed, but the inner 3 divs remain.

    <div class="account-content" data-editable-object="container">
        <div class="account-content-toggle" data-editable-object="active">
         // Active Content here 
        </div>

        <div class="account-content-toggle" data-editable-object="inactive">
        // Inactive Content here 
        </div>

        <div class="block-modal is-hidden" data-editable-object="modal"></div>
    </div>

Any help is appreciated! Thanks.

**Comment by jmacaluso711** [comment]
I'm having the same issue. any luck?

**Comment by wguldin** [comment]
Nope, sorry! We ended up not using salvattore.

**Comment by jmacaluso711** [comment]
Thanks for the response! In case you use it in the future: I ended up using registerGrid instead of recreateColumns after AJAX completes. That seemed to fix the problem
